apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-connector-cluster-meta-access
subjects:
  - kind: ServiceAccount
    namespace: eks-connector
    name: eks-connector
roleRef:
  kind: ClusterRole
  name: eks-connector-cluster-meta-access
  apiGroup: rbac.authorization.k8s.io